---
#------------------------------------------------------------------------
# CREATE A SECURITY POLICY FROM SERVICENOW
#------------------------------------------------------------------------
- hosts: panorama
  connection: local
  gather_facts: False
  collections:
    - paloaltonetworks.panos

  tasks:
    - name: "Create security policy"
      panos_security_rule:
        provider:
          ip_address: "{{ ansible_host }}"
          username: "{{ panorama_username }}"
          api_key: "{{ panorama_api_token }}"
        device_group: "{{ device_group }}"
        rule_name: "{{ rule_name }}"
        description: "{{ description }}"
        tag_name: ["{{ tag_name }}"]
        source_zone: ["{{ source_zone }}"]
        source_ip: ["{{ source_ip }}"]
        destination_zone: ["{{ destination_zone }}"]
        destination_ip: ["{{ destination_ip }}"]
        application: ["{{ application }}"]
        action: "{{ action }}"
